### ISSUE TITLE
Toast Notifications for Package Downloads and Updates

### ISSUE THREAD

**Issue by MaddyGuthridge** [ueffel/Keypirinha-PackageControl#14]
Since there isn't really an easy way to give feedback to a user when a command is executed with KeyPirinha (especially since the Tkinter module is removed), it might be useful to send notifications to a user when an important event happens. Here's a few example cases I could think of.
* A package installed successfully
* A download failed
* Updates are available for packages

This could be accomplished using something like the [win10toast-click](https://pypi.org/project/win10toast-click/) module.

If you want, I can look into potentially coding this in myself, since it seems simple enough.

**Comment by ueffel** [comment]
There are entries in the Keypirinha Console (F2) for everything you mentioned.

While it might be a good idea to be able to generate toast messages, it can't be done in a keypirinha plugin. The python package you mentioned uses pywin32, which is a binary package (not pure python). Those binary packages are problematic within keypirinha because it can be both 32 and 64bit. Also you cannot be sure that there aren't any ABI incompatibilities if you ship a binary library within a keypirinha package.

So I'm sorry but this is a won't fix.

One possibility would be that the keypirinha plugin API provides a way to generate toast messages. You could try to feature request this in the keypirinha main repository, but I think because keypirinha is targeted at advanced users (which can handle reading a console), it will likely not get implemented.

**Comment by MaddyGuthridge** [comment]
That's a shame that it's not that simple. Personally I'm hoping for nice simple messages for when things happen, because although I could open up the console, it would be much nicer to have the required information come to me, if that makes sense. I'm using Keypirinha to speed up my life, so optimisations like that make quite a huge difference for usability, especially for larger packages, such as EquatorKp (>15 MB), where downloads are less than instantaneous. I'll definitely add a feature request to the main Keypirinha repository.

**Comment by MaddyGuthridge** [comment]
[Link to issue on main Keypirinha page](https://github.com/Keypirinha/Keypirinha/issues/520)
