### ISSUE TITLE
"Update Repository List" doesn't retrieve all the packages (66/68)

### ISSUE THREAD

**Issue by TheLongLife** [ueffel/Keypirinha-PackageControl#15]
I'm not sure why but "Update Repository List" command only retrieves 66 packages.
`PackageControl.PackageControl: Package list loaded from 'ueffel's Package Repository' (66 packages)`

On [this page](https://ue.spdns.de/packagecontrol/) it says there are 68 packages available.

[KpTempoTap](https://github.com/MiguelGuthridge/KpTempoTap) is one of the 2 that are not retrieved.

**Comment by ueffel** [comment]
The 2 that are not retrieved are https://github.com/malys/keypirinha-gitlab and https://github.com/malys/keypirinha-jenkins because they have no release with a `.keypirinha-package` file (which means they cannot be installed via PackageControl). I already made issues in the repositories years ago. At this point I might as well delete them...

KpTempoTap is available to me:
![image](https://user-images.githubusercontent.com/2247384/143775257-5ffc98b8-bcb0-4ca6-9560-2886be41fb42.png)


You might wanna run `Update Repository List`. Because of the Github hiccup yesterday some data might be missing if you last retrieved the packages list in that time.

**Comment by TheLongLife** [comment]
I ran it again but nothing changed.
~Weirdly enough Jenkins is available to me but~ KpTempoTap still isn't available

~If I type Jenkins~ I just realized it's completely different package but it has the same name.
![image](https://user-images.githubusercontent.com/10586628/143776159-17e48cb7-110c-4fcf-8929-2b0861ca4c23.png)

If I type Tempo
![image](https://user-images.githubusercontent.com/10586628/143776078-546d3d83-aaf1-4f39-8619-bfaae44efeb8.png)

**Comment by ueffel** [comment]
The jenkins one is another Jenkins plugin, it is by another author.

Do you have TempoTap already installed? Then it wouldn't show up on `Install Package`. But it would show up für `Update Package` or `Remove Package`.

**Comment by TheLongLife** [comment]
> The jenkins one is another Jenkins plugin, it is by another author.

Yeah, I realized.

> Do you have TempoTap already installed? Then it wouldn't show up on `Install Package`. But it would show up für `Update Package` or `Remove Package`.

🤦‍♂️ Yup, it was already installed.  
What threw me off is the fact that when I typed just "tempo" there was no command corresponding with that package so I just assumed it wasn't installed without checking. Sorry, my bad.  
I guess that package is just not working properly.

**Comment by ueffel** [comment]
Alright.
I think I will delete the two packages without a release to avoid anymore confusion.
