### ISSUE TITLE
How to uninstall / reinstall PackageControl itself?

### ISSUE THREAD

**Issue by lursyy** [ueffel/Keypirinha-PackageControl#16]
Maybe I am blind, but I can't find how to uninstall PackageControl. I am experiencing the same problem as #8 and want to try a reinstall to fix it.

**Comment by ueffel** [comment]
If you select the `PackageControl: Reinstall Package` item you should be presented with Packagecontrol in the choices.
Another way you could do it: Select `PackageControl: Remove Package` then choose Packagecontrol and then use the code snippet from the readme to install it again.

Edit: But that is maybe not possible if the last.run file is damaged and you haven't got the fix for that yet. (#11)
Either you look for the last.run file and delete it or you just use the code snippet from the readme to install the newest version of packagecontrol over your current one.

**Comment by lursyy** [comment]
All of these options just result in PackageControl stuck in the "collecting packages" state:
![image](https://user-images.githubusercontent.com/13033130/162580981-285e2c42-782f-42b4-8a6f-d406d51cf234.png)

As mentioned above, I am trying to follow [this comment](https://github.com/ueffel/Keypirinha-PackageControl/issues/8#issuecomment-449690129) from #8.

**Comment by ueffel** [comment]
Anything in the console?

**Comment by lursyy** [comment]
Right, sorry for not thinking of that myself.
```
17:46:15.757 ** ERROR: PackageControl.PackageControl: Available packages could not be obtained:
 Traceback (most recent call last):
  File "C:\Users\luisb\AppData\Roaming\Keypirinha\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 410, in _get_available_packages
  File "C:\Users\luisb\AppData\Roaming\Keypirinha\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 512, in _get_last_run
  File "C:\Users\luisb\AppData\Roaming\Keypirinha\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 499, in _make_date
  File "lib\_strptime.py", line 577, in _strptime_datetime
  File "lib\_strptime.py", line 359, in _strptime
ValueError: time data '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00+0000' does not match format '%Y-%m-%dT%H:%M:%S%z'
17:46:15.757 ** ERROR: Error from PackageControl.PackageControl.on_suggest: <class 'TypeError'>: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\luisb\AppData\Roaming\Keypirinha\InstalledPackages\PackageControl.keypirinha-package\packagecontrol.py", line 205, in on_suggest
```

**Comment by ueffel** [comment]
Are you sure that you're using the latest release?
I'm asking because that error should be not be logged as error but as warning and should be handled in the latest release. You seem to be on release 1.0.2.
If you used the code snippet to install PackageControl again make sure it says `1.0.4` in the URL:

```python
[...]open("https://github.com/ueffel/Keypirinha-PackageControl/releases/download/1.0.4/"+p);[...]
```

**Comment by ueffel** [comment]
Also following [this comment](https://github.com/ueffel/Keypirinha-PackageControl/issues/11#issuecomment-717405236) from #11 
you could also just delete the `last.run` file, which should be located at `C:\Users\luisb\AppData\Local\Keypirinha\Packages\PackageControl\last.run` on your system.

**Comment by lursyy** [comment]
Ah, you are right. I didn't know I could use this command to update as well (since I couldn't use PackageControl for that). Maybe a note could be added to the installation section (i.e. "Installation / Update")

Thank you!!

**Comment by lursyy** [comment]
> Also following [this comment](https://github.com/ueffel/Keypirinha-PackageControl/issues/11#issuecomment-717405236) from #11 you could also just delete the `last.run` file, which should be located at `C:\Users\luisb\AppData\Local\Keypirinha\Packages\PackageControl\last.run` on your system.

Ah, good to know. So maybe this justifies a small "Troubleshooting" section? 1) (re)install latest version, 2) delete last.run?
