### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by danielkcz** [ueffel/Keypirinha-PackageControl#5]
Seems that site with packages is down? https://ue.spdns.de/packagecontrol/packages.json
I cannot reach it and I am not using any proxy.

**Comment by ueffel** [comment]
Is it still not working for you? Its working for me.

**Comment by danielkcz** [comment]
Now it's working, but I swear it wasn't :) I guess some hickup somewhere? Nevermind then :)

**Comment by danielkcz** [comment]
Btw, I am pretty much new to Keypirinha, just curious, when I run the import command, I get this output.

> 13:33:33.197 Plugin loaded: PackageControl.PackageControl (instance #3)
> 13:33:34.969 PackageControl.PackageControl: Package list loaded from 'ueffel's Package Repository' (26 packages)

I am a bit concerned about *(instance #3)*. I've run that command two times before because it was failing due to unreachable package list. Can that be some problem if the plugin is installed 3 times now? Can I remove previous instances in that case?

**Comment by ueffel** [comment]
I believe you that it wasn't working. This sadly happens sometimes :(

```
13:33:33.197 Plugin loaded: PackageControl.PackageControl (instance #3)
```
means that the Package got (re-)loaded. The number after `instance` just count the reloads. It does not mean that the package is loaded multiple times. What exactly happens, I do not know, you have to ask @polyvertex, but its nothing you should be worried about.

**Comment by polyvertex** [comment]
See [InstanceID](http://keypirinha.com/api/overview.html#instanceid). Basically yes, it is just a counter that is also used by KP to ensure that an old instance of a plugin would still try to populate its catalog while a new instance has been loaded. This may **technically** happen in very rare cases due to the way Python import machinery works. Nothing you should worry about indeed!
